services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_FILE_UPLOAD=50
    - HBOX_OPTIONS_ALLOW_ANALYTICS=false
    volumes:
      - ./data:/data/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local